name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build with dotnet
        run: dotnet build --configuration Debug
      - name: Run unit test
        run: dotnet test ThaiStringTokenizerTest /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover\" /p:Threshold=80 /p:ThresholdType=branch
      - name: prepare codecov
        run: pwd && cd ThaiStringTokenizerTest && pwd && curl -s https://codecov.io/bash > codecov && chmod +x codecov
      - name: upload codecoverage result
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: pwd && cd ThaiStringTokenizerTest && pwd && ./codecov -f "coverage.opencover.xml" -t $CODECOV_TOKEN
      # - name: Push to nuget
      #   env:
      #     NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      #   run: dotnet nuget push ThaiStringTokenizer/bin/Debug/*.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
